languageCode = "en-us"
title = "Gokhan Birinci - Software Engineer"
baseurl = "/"
theme = "aerial"
publishdir="public"

[params]
  name = "Gökhan Birinci"
  about = "I am the person who is passionate about Software Development, and I am developing web applications with mostly Java technologies. Currently, I am employeed as a Full Stack Software Engineer and I am trying to build fancy stuff with React."
  copyright = "Gokhan Birinci 2017"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "off"
  favicon = "/css/images/gbirinci.png"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/GokhanBirincii"

[[params.social]]
  medium = "Medium"
  icon = "medium"
  link = "https://medium.com/@gokhanbirincii"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/gokhanbirinci/"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/gokhanbirincii"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:me@gokhanbirinci.com"
